config/routes.rb
Rails.application.routes.draw do

  resources :beers do
    resources :reviews
  end

  resources :users, only: [:create, :new, :show]
  resources :reviews

  # Home Page
  root "static#home"

  # Login
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'

  # Logout
  delete '/logout', to: 'sessions#destroy'

  # Signup
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/auth/facebook/callback', to: 'sessions#create'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ActiveRecord::Base
    has_many :reviews
    has_many :users, through: :reviews

    validates :name, :style, :brewery, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :user
    belongs_to :beer
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password

    has_many :reviews
    has_many :beers, through: :reviews

    validates :name, presence: true
    validates :email, presence: true
    validates :email, uniqueness: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :require_login, :logged_in?
    before_action :require_login

    def current_user
        @current_user ||= User.find_by(:id => session[:user_id]) if session[:user_id]
    end
    

    def require_login
        unless current_user
            redirect_to root_path
        end
    end

    def logged_in?
        session[:user_id]
    end

end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

    before_action :require_login

    def new
        @beer = Beer.new
    end

    def index
        @beers = Beer.all
    end

    def show
        @beer = Beer.find_by(id: params[:id])
    end

    def create
        @beer = Beer.find_or_create_by(beer_params)
        if @beer.valid?
            @beer.save
            redirect_to @beer
        else
            render :new
        end
    end

    def update
        @beer = Beer.find_by(id: params[:id])
        @beer.update(beer_params)
        redirect_to @beer
    end

    private

    def beer_params
        params.require(:beer).permit(:name, :style, :brewery, :abv)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :require_login

    def index
        if params[:beer_id]
            @review = Beer.find(params[:beer_id]).review
        else
            @review = Review.all 
        end
    end

    def new
        @review = Review.new(:beer_id => params[:beer_id], :user_id => current_user.id)
    end

    def create
        @review = Review.new(review_params)
        if @review.save
            redirect_to beer_review_path(@review.beer, @review)
            render :new
        end
    end

    def edit
        @beer = Beer.find_by(id: params[:beer_id])
        if review.user_id != current_user.id
            redirect_to beers_path
        end
    end

    def update
        @review.update(review_params)
        redirect_to beer_review_path(@review.beer, @review)
    end

    def show
    end

    private

    def review_params
        params.require(:review).permit(:rating, :review, :price, :store, :date_of_purchase)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    skip_before_action :require_login

    def new
        @user = User.new
    end

    def create
        if authentication_hash = request.env["omniauth.auth"]
            @user = User.find_or_create_by_omniauth(authentication_hash)
            sessions[:user_id] = @user.id
            redirect_to @user
        else
            @user = User.find_by(email: params[:user][:email])
                if @user && @user.authenticate(params[:user][:password])
                session[:user_id] = @user.id 
                redirect_to @user
            else
                redirect_to '/signin'
            end
        end
    end

    def destroy
        session.clear
        redirect_to root_path
    end

    private

    def auth
        request.env['omniauth.auth']
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

    skip_before_action :require_login

    def home
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    skip_before_action :require_login

    def new
        @user = User.new
    end

    def show
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id 
            redirect_to @user
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beers/_form.html.erb
<%= form_for @beer do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :brewery %>
    <%= f.text_field :brewery %>
    <br>
    <%= f.label :style %>
    <%= f.text_field :style %>
    <br>
    <%#= f.label :ABV %>
    <%#= f.text_field :ABV %>
    <br>
    <br>
    <br>
    <%= f.submit %>
<% end %>

app/views/beers/edit.html.erb
<h1>Edit a beer's information:</h1>
<br>
<br>
<%= render partial: 'form' %>

app/views/beers/index.html.erb
<h1>All the beers...</h1>
<% @beers.each do |beer| %>
    <%= beer.name %>
<% end %>

app/views/beers/new.html.erb
<h1>Add a beer!</h1>
<br>
<%= render partial: 'form' %>

app/views/beers/show.html.erb
<h1><%= @beer.name %></h1>
<br>
Brewery: <%= @beer.brewery %>
<br>
Style: <%= @beer.style %>
<br>
<br>
<p><%= link_to 'Add a review', new_review_path %></p>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeerTrackerOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class='container'>
    <div class='row'>
      <div class='col-sm-8'>
        <%= yield %>
        </div>

        <div class='col-sm-4'>
          <div class='sidebar'>

          <% if logged_in?%>
            <%= link_to 'Home', user_path(current_user) %> |
            <%= link_to 'Logout', logout_path, method: "delete" %>

          <% else %>

            <%= link_to 'Sign Up', signup_path %> |
            <%= link_to 'Log In', signin_path %> |
            <%= link_to('Log in with Github', '/auth/github') %>

        <% end %>
        </div>
      </div>
    </div>
    
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for [@review] do |f| %>
    <%#= beer_id_field(@review) %>

        <%= f.label :rating %>
        <%= f.number_field :rating %>
        <br>
        <%= f.label :review %>
        <%= f.text_area :review %>
        <br>
        <%= f.label :price %>
        <%= f.number_field :price %>
        <br>
        <br>
        <br>
        <%= f.submit %>

<% end %>

app/views/reviews/edit.html.erb
<h1>Edit your review!</h1>

<%= render partial: 'form' %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>
<% @reviews.each do |review| %>
User: <%= review.user.name %>

app/views/reviews/new.html.erb
<h1>Add your review!</h1>

<%= render partial: 'form' %>

app/views/reviews/show.html.erb
<h1>Review</h1>
<p><%= @review.text %></p>
<% if current_user == @review.user %>
    <%= link_to "Edit the Review", edit_beer_review_path(@review.beer, @review) %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up!</h1>
<%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <br>
    <br>
    <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.name %>! </h1>
<br>
<h2>Your beer list!</h2>
<br>
<br>
<p><%= link_to 'Add a new beer', new_beer_path %></p>